export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/*
 * POST /api/report/email
 *
 * Body: {
 *   to: string,
 *   subject: string,
 *   note?: string,
 *   filename: string,
 *   csv: string,
 *   summary?: { label: string; value: string }[]
 * }
 *
 * If RESEND_API_KEY is set, the report is sent as a real email with the
 * CSV attached (via Resend's REST API — no SDK dependency). Otherwise the
 * route returns a `mailto:` URL carrying the summary so the client can
 * hand off to the user's own mail app. Either way the caller gets a
 * usable result.
 */

type Body = {
  to?: string;
  subject?: string;
  note?: string;
  filename?: string;
  csv?: string;
  summary?: { label: string; value: string }[];
};

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

function summaryText(
  note: string,
  summary: { label: string; value: string }[]
): string {
  const lines: string[] = [];

  if (note) lines.push(note, "");

  if (summary.length > 0) {
    lines.push("Summary");
    for (const item of summary) lines.push(`  ${item.label}: ${item.value}`);
    lines.push("");
  }

  lines.push("— Generated by ChainSight");
  return lines.join("\n");
}

export async function POST(request: Request) {
  let body: Body;

  try {
    body = (await request.json()) as Body;
  } catch {
    return Response.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const to = (body.to ?? "").trim();
  const subject = (body.subject ?? "ChainSight report").trim();
  const note = (body.note ?? "").trim();
  const filename = (body.filename ?? "chainsight-report.csv").trim();
  const csv = body.csv ?? "";
  const summary = Array.isArray(body.summary) ? body.summary : [];

  if (!EMAIL_RE.test(to)) {
    return Response.json(
      { error: "A valid recipient email is required" },
      { status: 400 }
    );
  }

  const text = summaryText(note, summary);
  const apiKey = process.env.RESEND_API_KEY;

  if (!apiKey) {
    // Graceful fallback: let the browser open the user's mail client.
    const mailto =
      `mailto:${encodeURIComponent(to)}` +
      `?subject=${encodeURIComponent(subject)}` +
      `&body=${encodeURIComponent(
        `${text}\n\n(The full data set is a CSV export from ChainSight — ` +
          `attach it from your download folder, or configure RESEND_API_KEY ` +
          `to have ChainSight send it directly.)`
      )}`;

    return Response.json({ sent: false, mailto });
  }

  try {
    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from:
          process.env.REPORT_FROM_EMAIL ||
          "ChainSight <onboarding@resend.dev>",
        to: [to],
        subject,
        text,
        attachments: [
          {
            filename,
            content: Buffer.from(csv, "utf-8").toString("base64"),
          },
        ],
      }),
    });

    if (!response.ok) {
      const detail = await response.text();
      console.error("Resend rejected the report email:", detail);
      return Response.json(
        { error: "The mail service rejected the message." },
        { status: 502 }
      );
    }

    return Response.json({ sent: true });
  } catch (error) {
    console.error("Report email failed:", error);
    return Response.json(
      { error: "Could not reach the mail service." },
      { status: 502 }
    );
  }
}
